// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnINNw_27IV2Bc8UX7L65faMBxCYv8ORE',
    appId: '1:12012106326:web:d6b2af1d0eac229644c1f7',
    messagingSenderId: '12012106326',
    projectId: 'elimupath-733f9',
    authDomain: 'elimupath-733f9.firebaseapp.com',
    storageBucket: 'elimupath-733f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_VHTEj9t9rSTN_LRhQQxT_IrPugIhWbE',
    appId: '1:12012106326:android:f973b7bf82e3d38544c1f7',
    messagingSenderId: '12012106326',
    projectId: 'elimupath-733f9',
    storageBucket: 'elimupath-733f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiyeHPXlDMpmu2M7w4_LbJz3UqqoU4u18',
    appId: '1:12012106326:ios:d5f004ba4da7857444c1f7',
    messagingSenderId: '12012106326',
    projectId: 'elimupath-733f9',
    storageBucket: 'elimupath-733f9.firebasestorage.app',
    iosBundleId: 'com.example.group39FinalProjectSubmission',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiyeHPXlDMpmu2M7w4_LbJz3UqqoU4u18',
    appId: '1:12012106326:ios:d5f004ba4da7857444c1f7',
    messagingSenderId: '12012106326',
    projectId: 'elimupath-733f9',
    storageBucket: 'elimupath-733f9.firebasestorage.app',
    iosBundleId: 'com.example.group39FinalProjectSubmission',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnINNw_27IV2Bc8UX7L65faMBxCYv8ORE',
    appId: '1:12012106326:web:832c061fbce7f5ed44c1f7',
    messagingSenderId: '12012106326',
    projectId: 'elimupath-733f9',
    authDomain: 'elimupath-733f9.firebaseapp.com',
    storageBucket: 'elimupath-733f9.firebasestorage.app',
  );
}
